name: Windows

on:
  push:
    branches:
      - main
      - python-decoupling
  pull_request:

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows 2025 [Release]",
            os: windows-2025,
            build-type: "Release"
          }
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Python Test Dependencies
      run: python -m pip install pytest

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{ github.workspace }} -DWARNINGS_AS_ERRORS=ON -DPYTHON_ENFORCE_TESTS=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel --config ${{matrix.config.build-type}} --target everything

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -C ${{matrix.config.build-type}} --output-on-failure
